googleapis/google-auth-library-ruby

googleauth.gemspec

Updates to reflect status on https://gemnasium.com/google/google-auth-library-ruby

Updates the dependencies

---

lib/googleauth.rb
lib/googleauth/credentials_loader.rb
lib/googleauth/user_refresh.rb
spec/googleauth/get_application_default_spec.rb
spec/googleauth/service_account_spec.rb
spec/googleauth/user_refresh_spec.rb

Ruby auth add user creds

---

lib/googleauth/iam.rb
spec/googleauth/iam_spec.rb

Adds an implementation of IAMCredentials

---

googleauth.gemspec

see also: https://github.com/intridea/multi_json/blob/master/CHANGELOG.md#1111

relax the constraint of dependent version of multi_json

---

.rubocop_todo.yml
Gemfile
lib/googleauth.rb
lib/googleauth/web_user_authorizer.rb
spec/googleauth/client_id_spec.rb
spec/googleauth/web_user_authorizer_spec.rb
spec/spec_helper.rb

2nd set of changes for 3LO support - WebUserAuthorizer.

Round 2 of 3LO support - web flow

---

.travis.yml
lib/googleauth.rb
lib/googleauth/client_id.rb
lib/googleauth/compute_engine.rb
lib/googleauth/credentials_loader.rb
lib/googleauth/iam.rb
lib/googleauth/scope_util.rb
lib/googleauth/service_account.rb
lib/googleauth/signet.rb
lib/googleauth/stores/redis_token_store.rb
lib/googleauth/token_store.rb
lib/googleauth/user_authorizer.rb
lib/googleauth/user_refresh.rb
lib/googleauth/version.rb
lib/googleauth/web_user_authorizer.rb
spec/googleauth/apply_auth_examples.rb
spec/googleauth/client_id_spec.rb
spec/googleauth/compute_engine_spec.rb
spec/googleauth/get_application_default_spec.rb
spec/googleauth/scope_util_spec.rb
spec/googleauth/service_account_spec.rb
spec/googleauth/signet_spec.rb
spec/googleauth/user_authorizer_spec.rb
spec/googleauth/user_refresh_spec.rb
spec/googleauth/web_user_authorizer_spec.rb

If this project is still actively maintained, I added the latest ruby to the matrix build.
also:
* updated rubocop and applied styling
* made small test refactorings (using the expect block notation)
* made a small refactor to remove an unnecessary ``return credentials``
* bumped the version

added ruby 2.3 to travis w/ other small changes.

---

README.md

A cleaned up version from #62.

Add service account example

---

lib/googleauth/service_account.rb
lib/googleauth/user_refresh.rb
spec/googleauth/service_account_spec.rb
spec/googleauth/user_authorizer_spec.rb
spec/googleauth/user_refresh_spec.rb
spec/googleauth/web_user_authorizer_spec.rb

This change is a more complete update based on PR #70.

Upgrade to new token URI

---

CONTRIBUTING.md

This repairs Markdown links which were broken.

CONTRIBUTING: Unbreak CLA links

---

lib/googleauth/user_authorizer.rb

Fix typo constant

---

Gemfile
lib/googleauth/user_refresh.rb

* Fix for google-style 0.3.0 change to Style/WordArray.
* Update google-style dependency to 0.3.

Fix Rubocop errors

---

.rubocop.yml
lib/googleauth/web_user_authorizer.rb

fix: Arity of WebUserAuthorizer#get_credentials should be compatible with base class

---

.kokoro/release.cfg
Gemfile
Rakefile

Fixes corresponding to the following from the signet repo:
* https://github.com/googleapis/signet/pull/148
* https://github.com/googleapis/signet/pull/149
* https://github.com/googleapis/signet/pull/150
* https://github.com/googleapis/signet/pull/151

Fixes to release scripts

---

.kokoro/continuous/linux.cfg
.kokoro/continuous/post.cfg
.kokoro/presubmit/linux.cfg
README.md
Rakefile
lib/googleauth/application_default.rb
lib/googleauth/service_account.rb
lib/googleauth/user_refresh.rb
rakelib/link_checker.rb

* add post build, which runs [linkinator](https://github.com/JustinBeckwith/linkinator) against repo and https://googleapis.dev/ruby/googleauth/latest/index.html
* elongate http://goo.gl/mkAHpZ

chore: run linkinator on merges to master

---

.rubocop.yml
lib/googleauth/user_authorizer.rb
spec/googleauth/user_authorizer_spec.rb

Add whitelisted 'postmessage' to valid redirect URIs

---

googleauth.gemspec

chore: update github url

---

CHANGELOG.md
lib/googleauth/version.rb

* Support for validating ID tokens.
* Fixed header application of ID tokens from service accounts.
<details><summary>Commits since previous release</summary><pre><code>commit 4df620978cf38b40ffbacbd9d04b2870b2faab94
Author: Daniel Azuma <dazuma@google.com>
Date:   Wed Jun 17 08:13:42 2020 -0700
feat: Support for ID token validation
commit a3f3b994ab2180af573f8b3680d4da0840e200ee
Author: Daniel Azuma <dazuma@google.com>
Date:   Tue Jun 16 13:35:39 2020 -0700
fix: Service account credentials properly apply ID tokens
commit 9bcac01574d539e281326beaa25d19e07002b525
Author: Daniel Azuma <dazuma@google.com>
Date:   Sat Apr 11 15:14:02 2020 -0700
Release google-auth-library-ruby 0.12.0 (#261)
* Support for ID token credentials.
* Support reading quota_id_project from service account credentials. …

Release google-auth-library-ruby 0.13.0

---

.rubocop.yml
Gemfile
README.md
googleauth.gemspec
lib/googleauth/credentials.rb
lib/googleauth/credentials_loader.rb
lib/googleauth/iam.rb
lib/googleauth/id_tokens/key_sources.rb
lib/googleauth/id_tokens/verifier.rb
lib/googleauth/scope_util.rb
lib/googleauth/service_account.rb
lib/googleauth/signet.rb
lib/googleauth/stores/file_token_store.rb
lib/googleauth/stores/redis_token_store.rb
lib/googleauth/web_user_authorizer.rb

* Updated the gemspec's required_ruby_version to >= 2.5
* Updated google-style to ~> 1.25.1
* Resolved all rubocop issues

feat: Drop support for Ruby 2.4 and add support for Ruby 3.0

---

.repo-metadata.json

chore: Fill in missing fields in repo-metadata

---

lib/googleauth/service_account.rb
spec/googleauth/service_account_spec.rb

feat: make new_jwt_token public in order to fetch raw token directly

---

googleauth.gemspec
lib/googleauth/application_default.rb
lib/googleauth/compute_engine.rb
spec/googleauth/compute_engine_spec.rb

chore: Drop memoist

---

README.md
lib/googleauth/application_default.rb
lib/googleauth/credentials_loader.rb

docs: improve ADC related error and warning messages

---

.kokoro/presubmit/samples.cfg
.toys/.lib/repo_context.rb
lib/googleauth/id_tokens.rb

I hope this will get the samples tests passing again.

tests: fix kokoro environment loading to get credentials from secret manager

---

lib/googleauth.rb
lib/googleauth/api_key.rb
lib/googleauth/default_credentials.rb
test/api_key_test.rb

Implementation of Google API Key authentication.

feat: add API key credentials

---

lib/googleauth/credentials.rb
spec/googleauth/credentials_spec.rb

fix: support Pathname for cred loading
