- spec/googleauth/get_application_default_spec.rb
- spec/googleauth/service_account_spec.rb
- spec/googleauth/user_refresh_spec.rb
rspec spews a warning when using raise_error without a specific error;
add "RuntimeError" to all of these occurrences.
> Fix 'raise_error' WARNINGs.

- spec/googleauth/get_application_default_spec.rb
The environment variables in the 'fails if env vars are set' test
were not actually being set because they used a nonexistent hash key
(which has the effect of unsetting the environment variable).
> Fix a failing test introduced in #28.

- googleauth.gemspec
- lib/googleauth.rb
- lib/googleauth/credentials_loader.rb
- spec/googleauth/get_application_default_spec.rb
- spec/googleauth/service_account_spec.rb
- spec/googleauth/user_refresh_spec.rb
The path is:
- windows: %ProgramData%\Google\Auth\application_default_credentials.json
- other: /etc/google/auth/application_default_credentials.json
> Add support for a system default credentials file.

- CHANGELOG.md
You referred non-existing person.
https://github.com/haabator
↓
https://github.com/haabaato
> fix typo of a contributor's name

- .travis.yml
- CHANGELOG.md
- Gemfile
- README.md
- googleauth.gemspec
- lib/googleauth/signet.rb
- lib/googleauth/version.rb
- lib/googleauth/web_user_authorizer.rb
- spec/googleauth/apply_auth_examples.rb
- spec/googleauth/compute_engine_spec.rb
- spec/googleauth/get_application_default_spec.rb
- spec/googleauth/service_account_spec.rb
- spec/googleauth/signet_spec.rb
- spec/googleauth/user_refresh_spec.rb
- spec/spec_helper.rb
Updates to release 0.5 for the user authorizer functionality.
Includes updates to tests to use webmock instead of Faraday stubs. Using faraday's stubs turns out to be fragile as data isn't fully normalized (content of env changes depending on the style of the call, even if they're semantically equivalent.) Using webmock ends up being simpler and safer anyway.
> Prep for 0.5 release

- googleauth.gemspec
- lib/googleauth/credentials_loader.rb
Fix for https://github.com/google/google-auth-library-ruby/issues/55
Currently only some of the possible host_os values (i.e. Windows and mswin) are used to identify whether the library is running on a windows machine. There are many other possible values that could signify a windows machine. E.g. my machine has 'mingw32'. Using the OS.windows? seems like a more reliable way to identify this.
Please note: this fix is for representational purposes only. I have validated the code fragments individually on my machine, but I haven't validated it by building this full repo.
> Fix for ADC not working on some windows machines

- lib/googleauth/signet.rb
- spec/googleauth/apply_auth_examples.rb
This makes the library HTTP2-compatible without breaking HTTP/1.1 support.
> Use lowercase :authorization for metadata key

- lib/googleauth.rb
In DefaultCredentials.read_creds, when the environment variable referenced by CredentialsLoader::ACCOUNT_TYPE_VAR is not set, the resulting error message used the unqualified constant ACCOUNT_TYPE_VAR. That was giving an uninitialized constant error.
> Fix uninitialized constant in DefaultCredentials

- README.md
> google-api-ruby-client now uses google-auth-library-ruby

- googleauth.gemspec
Faraday 0.9 is two years old. Reading through https://github.com/lostisland/faraday/releases, this should probably be updated.
This is an attempt to deal with #99.
> Update faraday dependency

- lib/googleauth/compute_engine.rb
- lib/googleauth/signet.rb
- lib/googleauth/user_refresh.rb
- spec/googleauth/compute_engine_spec.rb
- spec/googleauth/user_refresh_spec.rb
- implement https://github.com/google/google-auth-library-ruby/issues/89
- retry when request failed or timeout in `GCECredentials#fetch_access_token` and `UserRefreshCredentials#revoke!`
- when give up retrying, raise `Signet::AuthorizationError` with the string of `original_error.inpsect`
> Retry http request when unexpected error occurs

- lib/googleauth/credentials.rb
- spec/googleauth/credentials_spec.rb
- spec/spec_helper.rb
Credentials.default has a bug where it returns an empty array if no matches were found when looking up keyfile info in `PATH_ENV_VARS`, `JSON_ENV_VARS`, or `DEFAULT_PATHS`. This is because of how the implementation was changed when migrating from google-cloud-ruby. The fix is to return `nil` if no matches are found from the various lookup methods.
> Fix Credentials.default

- lib/googleauth/service_account.rb
- spec/googleauth/service_account_spec.rb
Alternative to https://github.com/google/google-auth-library-ruby/pull/88 that doesn't fail earlier tests. Unescapes only the specific `\n` sequence, and doesn't convert existing newlines to plain space characters. Also removes enclosing quotes if present.
> Unescape private_key loaded from ENV

- lib/googleauth/application_default.rb
- Modify to clear the cache of the result of `GCECredentials.on_gce?` if `GCECredentials.on_gce?` returns false.
- This change resolves the problem  which `GCECredentials.on_gce?`  keeps returning `false` even  though `GCECredentials::COMPUTE_CHECK_URI` is active, as I explained in the following.
- `GCECredentials.on_gce?` caches the result as a Class instance variable. So, once `GCECredentials.on_gce?` is called,  this method keeps returning a same value in a same ruby process.
- But, `GCECredentials.on_gce?` returns false occasionally even though `COMPUTE_CHECK_URI` is active.
- So, if `GCECredentials.on_gce?` returns `false` in the first time call, `GCECredentials.on_gce?` keeps returning `false` within a same ruby process.
- I faced this problem when I developed an ETL tool which …
> clear cache of the result of GCECredentials.on_gce? when GCECredentials.on_gce? returns false.

- googleauth.gemspec
Was lead here because my `bundle outdated` showed this was out of date on my app. No breaking changes in the changelog for this gem, so it should be a trivial change.
> Update os gem dependency

- lib/googleauth/credentials_loader.rb
- lib/googleauth/version.rb
Some of the call sites are calling `CredentialsLoader.warn_if_cloud_sdk_credentials` as a module method. Need to define the method on the module object.
Also bumped the version number because the latest release is actually 0.6.2. It looks like the last time this was released, the update didn't get committed and tagged.
> Fix sdk credentials warning

- CHANGELOG.md
- lib/googleauth/default_credentials.rb
- lib/googleauth/version.rb
Fix for https://github.com/google/google-auth-library-ruby/issues/153
> fix CLIENT_ID_VAR reference in DefaultCredentials

- lib/googleauth/user_refresh.rb
- spec/googleauth/user_authorizer_spec.rb
- spec/googleauth/user_refresh_spec.rb
Looks like https://github.com/google/google-auth-library-ruby/pull/147/files has changed the auth [revocation URL](https://github.com/google/google-auth-library-ruby/blob/43d175f65847e7235e4a7964446443d3b42ea20f/lib/googleauth/user_refresh.rb#L51) from `https://accounts.google.com/o/oauth2/revoke` to `https://oauth2.googleapis.com/revoke` and the new URL seems to respond with a 404. This is because [/revoke should be invoked with a POST](https://github.com/GoogleCloudPlatform/google-cloud-common/issues/260#issuecomment-413232751).
Update The HTTP method for /revoke to be a POST.
> Fix auth token revocation (broken since 0.6.3)

- googleauth.gemspec
- lib/googleauth/compute_engine.rb
I work on a project that had the following error from Google Auth:
```
NoMethodError: undefined method `all_memoized_structs' for Class:Class
/gems/memoist-0.14.0/lib/memoist.rb:67 in memoized_structs
/gems/memoist-0.14.0/lib/memoist.rb:84 in flush_cache
/gems/memoist-0.14.0/lib/memoist.rb:63 in unmemoize_all
/gems/googleauth-0.6.6/lib/googleauth/application_default.rb:63 in get_application_default
```
We have upgraded Memoist to 0.16.0 to include the fix for https://github.com/matthewrudy/memoist/issues/63. This branch changes theGoogle Auth dependency to the upgraded version to avoid this for all other users.
> Upgrade Memoist and cleanup Robucop minor failures

- CHANGELOG.md
- lib/googleauth/credentials.rb
- lib/googleauth/credentials_loader.rb
- lib/googleauth/json_key_reader.rb
- lib/googleauth/service_account.rb
- lib/googleauth/user_refresh.rb
- lib/googleauth/version.rb
- spec/googleauth/credentials_spec.rb
- spec/googleauth/get_application_default_spec.rb
- spec/googleauth/service_account_spec.rb
- spec/googleauth/user_refresh_spec.rb
https://github.com/googleapis/google-auth-library-ruby/issues/90
https://github.com/googleapis/google-cloud-ruby/issues/951
May be helpful for https://github.com/googleapis/google-cloud-ruby/issues/2013
The library will attempt to grab the project id in the following order
1) ENV['GOOGLE_APPLICATION_CREDENTIALS']
2) ENV['GOOGLE_CLOUD_PROJECT']
3) ~/.config/gcloud/application_default_credentials.json
4) System default path
5) gcloud config config-helper
> Load project id from environment variables, service accounts, and cloud sdk

- lib/googleauth/credentials_loader.rb
Remove the warning, as it is not necessary.
[refs googleapis/google-auth-library-ruby#90] [refs googleapis/google-api-ruby-client#750]
> Remove warning while looking up project_id

- .rubocop.yml
- lib/googleauth/application_default.rb
- lib/googleauth/compute_engine.rb
- lib/googleauth/credentials.rb
- lib/googleauth/credentials_loader.rb
- lib/googleauth/default_credentials.rb
- lib/googleauth/service_account.rb
- lib/googleauth/signet.rb
- lib/googleauth/user_refresh.rb
- spec/googleauth/credentials_spec.rb
- spec/googleauth/get_application_default_spec.rb
- spec/googleauth/service_account_spec.rb
- spec/googleauth/signet_spec.rb
The various `make_creds` and `from_*` methods that create credentials objects now recognize two more options:
* **:default_connection** The `Faraday::Connection` to use when making calls to refresh tokens.
* **:connection_builder** A `Proc` that is called when a token refresh needs to be done. Should return a `Faraday::Connection`.
These may be used, for example, to configure the connection suitably to connect through a proxy.
Fixes #131
> Support configuration of the connection object used to fetch tokens

- README.md
Please consider adding this example to Readme as this shows simple way how to authenticate with ENV variables "GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_EMAIL", "GOOGLE_ACCOUNT_TYPE", "GOOGLE_PRIVATE_KEY"
Thank you!
> Added example for auth with ENV vars

- lib/googleauth/credentials_loader.rb
Fixes https://github.com/googleapis/google-auth-library-ruby/issues/192
> switch gcloud command to IO.popen from backticks

- .rubocop.yml
- CHANGELOG.md
- Gemfile
- googleauth.gemspec
- lib/googleauth.rb
- lib/googleauth/application_default.rb
- lib/googleauth/client_id.rb
- lib/googleauth/compute_engine.rb
- lib/googleauth/credentials.rb
- lib/googleauth/credentials_loader.rb
- lib/googleauth/default_credentials.rb
- lib/googleauth/iam.rb
- lib/googleauth/json_key_reader.rb
- lib/googleauth/scope_util.rb
- lib/googleauth/service_account.rb
- lib/googleauth/signet.rb
- lib/googleauth/stores/file_token_store.rb
- lib/googleauth/stores/redis_token_store.rb
- lib/googleauth/token_store.rb
- lib/googleauth/user_authorizer.rb
- lib/googleauth/user_refresh.rb
- lib/googleauth/version.rb
- lib/googleauth/web_user_authorizer.rb
* Edit CHANGELOG to mimic format in https://github.com/googleapis/google-cloud-ruby. This allows releasetool to properly place the new CHANGELOG entry, as well as increasing consistency across libraries.
* Enforce double_quotes for string literals. We will have to do this eventually anyway, and this allows [releasetool](https://github.com/googleapis/releasetool/blob/8485dbad3d5eb768bde4b092516dddd6f976ddca/releasetool/commands/start/ruby.py#L171) to update the version.
> prepare for autorelease

- CHANGELOG.md
- lib/googleauth/version.rb
* Silence unnecessary gcloud warning
* Treat empty credentials environment variables as unset
This pull request was generated using releasetool.
> Release google-auth-library-ruby 0.8.1

- .rubocop.yml
- README.md
- googleauth.gemspec
This pull request bumps the minimum supported Ruby version from 1.9 to 2.3.
Ruby on Rails CI for 5-2-stable with Ruby 2.2.10 and google-auth-library-ruby 0.8.1 has been failing
https://travis-ci.org/rails/rails/jobs/512320216#L1788
```ruby
NOT_FOUND_ERROR = <<~ERROR_MESSAGE.freeze
```
Since #203 introduces indented here document `<<~` which
is available only for Ruby 2.3 https://bugs.ruby-lang.org/issues/9098
Refer https://github.com/googleapis/google-auth-library-ruby/issues/111#issuecomment-477966192
> Bump the minimum supported Ruby version from 1.9 to 2.3

- lib/googleauth/credentials.rb
- spec/googleauth/credentials_spec.rb
This PR updates how credentials are detected from environment variables. It allows for an environment variable to contain either the path to a file, or the JSON contents.
This simplified approach matches how environment variables are used in Google Cloud, and is a step towards replacing the use of constants for values that users are meant to change.
This change should not break backwards compatibility.
> Credentials Environment Variable Refactor

- .rubocop.yml
- lib/googleauth/credentials.rb
- spec/googleauth/credentials_spec.rb
Update Credentials to use methods for values that are intended to be changed by users, replacing constants. The methods will check the constants for values if the methods have not been set. This should allow for this change to be backwards compatible, as users will opt in to using the new behavior.
> Credentials: Use methods instead of constants

- lib/googleauth/credentials_loader.rb
Without this change, creating the default credentials when gcloud credentials are not set results in the following on stderr:
```
$ ruby -e 'require "googleauth"; Google::Auth::Credentials.default'
ERROR: (gcloud.config.config-helper) You do not currently have an active account selected.
Please run:
$ gcloud auth login
to obtain new credentials, or if you have already logged in with a
different account:
$ gcloud config set account ACCOUNT
to select an already authenticated account to use.
```
See also googleapis/google-cloud-ruby#2986.
> Fix the gcloud command to avoid spamming stderr when unauthorized.

- lib/googleauth/web_user_authorizer.rb
- spec/googleauth/web_user_authorizer_spec.rb
This PR adds the ability to specify custom `state` key-value pairs so that they can be forwarded to the callback.
Closes https://github.com/googleapis/google-auth-library-ruby/issues/217
> Allow specifying custom state key-values

- lib/googleauth/signet.rb
- spec/googleauth/signet_spec.rb
Adds a retry block around orig_fetch_access_token! and some tests to describe the behaviour.
We've found that occasionally, while querying the api server for whatever reason, a `503 - UNAVAILABLE` error is returned. Retrying the request typically yields a successful response.
After reading [the docs for the Google Cloud API](https://cloud.google.com/apis/design/errors#error_retries), it appears as though retrying the request is a valid course of action after receiving this error response. It looks like this is already the approach taken in [other places in the code](https://github.com/googleapis/google-auth-library-ruby/blob/master/lib/googleauth/compute_engine.rb#L90).
> Add retry on error for fetch_access_token!

- README.md
Travis is not configured for this repo anymore so this PR removes the build status image from the README.
/cc @TheRoyalTnetennba
> Remove Travis build status

- lib/googleauth/compute_engine.rb
- spec/googleauth/compute_engine_spec.rb
In GKE 1.13.7-gke.8, COMPUTE_CHECK_URI(http://169.254.169.254) requires the header "Metadata-Flavor": "Google".
```
* Rebuilt URL to: http://169.254.169.254/
*   Trying 169.254.169.254...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> GET / HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Wed, 07 Aug 2019 14:33:12 GMT
< Content-Length: 94
< 
GKE Metadata Server encountered an error: Missing required header "Metadata-Flavor": "Google"
* Connection #0 to host 169.254.169.254 left intact
* Rebuilt URL to: http://169.254.169.254/
*   Trying 169.254.169.254...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> GET / HTTP/1.1
> …
```
> GKE Metadata Server requires header "Metadata-Flavor": "Google" at COMPUTE_CHECK_URI

- lib/googleauth/credentials.rb
- lib/googleauth/signet.rb
Fixes https://github.com/googleapis/google-auth-library-ruby/issues/227.
> Set instance variables at initialization to avoid spamming rake warnings.

- lib/googleauth/compute_engine.rb
According to https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
>  Field names are case-insensitive
Some proxies like envoy for istio when setup in a GKE pod, they intercept all traffic and they does convert all headers to lower case. This made the check `on_gce?` fails because the response has these headers
```
content-type: application/text
metadata-flavor: Google
server: envoy
date: Sun, 21 Jul 2019 11:13:04 GMT
content-length: 17
x-envoy-upstream-service-time: 0
```
And from this response it is clear that the header `Metadata-Flavor` has been changed to `metadata-flavor`
> Make the header check case insensitive

- lib/googleauth/credentials_loader.rb
- spec/googleauth/credentials_spec.rb
Currently, this library always issues the following warning when using end user credentials:
> Your application has authenticated using end user credentials from
> Google Cloud SDK. We recommend that most server applications use service
> accounts instead. If your application continues to use end user
> credentials from Cloud SDK, you might receive a "quota exceeded" or "API
> not enabled" error. For more information about service accounts, see
> https://cloud.google.com/docs/authentication/
This is helpful, but it can wear thin during local development. This
commit adds an environment variable that the library user can set if the
warning's annoying; if they care enough to read the message properly and
to set the environment variable, they probably know what they're doing
with it.
@dazuma …
> support an environment variable to suppress Cloud SDK credentials warnings

- lib/googleauth/compute_engine.rb
Keep `open_timeout` low to keep the "fail-fast" behavior on non-gce hosts. But increase overall `timeout` to reduce false negatives since some metadata service instances can take a few moments to warm up. (In particular, this warmup behavior is sometimes observed on Titanium-based hosting.) This matches the settings we converged on in the google-cloud-env gem.
Fixes #226
> fix: Increase metadata timeout, matching the logic in google-cloud-env

- Gemfile
- README.md
- googleauth.gemspec
This is not going to pass tests until signet 0.12.0 is released, but opening the PR so we have all the proposals available.
> Require Ruby 2.4 and Signet 0.12

- CHANGELOG.md
Note: This release now requires Ruby 2.4 or later
* Increase metadata timeout to improve reliability in some hosting environments
* Support an environment variable to suppress Cloud SDK credentials warnings
* Make the header check case insensitive
* Set instance variables at initialization to avoid spamming warnings
* Pass "Metadata-Flavor" header to metadata server when checking for GCE
<details><summary>Commits since previous release</summary><pre><code>commit fe4220244c196a626d43093e6d806b02af983c3b
Author: Daniel Azuma <dazuma@google.com>
Date:   Wed Oct 9 11:25:44 2019 -0700
Require Ruby 2.4 and Signet 0.12 (#236)
commit 5523a75fc379d2d4554e7edd80490454181b6a69
Author: Daniel Azuma <dazuma@google.com>
Date:   Wed Oct 9 10:55:44 2019 -0700
Fixes to release scripts (#238)
commit …
> Release google-auth-library-ruby 0.10.0

- rakelib/repo_metadata.rb
Change https://googleapis.dev/ruby/googleauth/0.10.0/index.html to https://googleapis.dev/ruby/googleauth/v0.10.0/index.html
> add v to version in docs url to keep consistent with other ruby libraries

- CHANGELOG.md
- lib/googleauth/version.rb
* Support Faraday 1.x.
* Allow special "postmessage" value for redirect_uri.
<details><summary>Commits since previous release</summary><pre><code>commit de8e9e42afc74fef211147154fd366f0f2c69757
Author: d-m-u <16326669+d-m-u@users.noreply.github.com>
Date:   Mon Feb 24 17:23:05 2020 -0500
feat: support Faraday 1.x
commit d80900156a02f5d79666fe9a11fb610a1443f34c
Author: Chris Smith <quartzmo@gmail.com>
Date:   Mon Dec 2 10:11:13 2019 -0700
Add whitelisted 'postmessage' to valid redirect URIs (#249)
closes: #92
commit 4928d44072bec6645251bddf19b06810734f877a
Author: Graham Paye <paye@google.com>
Date:   Tue Oct 29 16:08:50 2019 -0700
add v to version in docs url (#246)
commit b33b25c3fb76f1807d4790ef8b72ed783da8e99c
Author: Graham Paye <paye@google.com>
Date:   Thu Oct 17 18:12:43 2019 -0700 …
> Release google-auth-library-ruby 0.11.0

- lib/googleauth/credentials.rb
- lib/googleauth/json_key_reader.rb
- lib/googleauth/service_account.rb
- spec/googleauth/credentials_spec.rb
- spec/googleauth/service_account_spec.rb
We've been asked to read `quota_project_id` from credentials, and set the `X-Goog-User-Project` header accordingly if it is present. (This is for a 3LO case where billing/quota project may be different from the target/data project.)
This PR reads the new field from the JSON credentials file (if present), and sets it on a field in the credentials object (`Google::Auth::Credentials` for gRPC clients, and `Signet::OAuth2::Client` subclasses for REST clients). Separately, the client libraries themselves will need to check for this field and set the header if needed.
> feat: read quota_project_id from credentials

- Gemfile
- googleauth.gemspec
- lib/googleauth/compute_engine.rb
- lib/googleauth/credentials.rb
- lib/googleauth/service_account.rb
- lib/googleauth/signet.rb
- lib/googleauth/user_refresh.rb
- spec/googleauth/apply_auth_examples.rb
- spec/googleauth/compute_engine_spec.rb
- spec/googleauth/service_account_spec.rb
- spec/googleauth/signet_spec.rb
- spec/googleauth/user_refresh_spec.rb
Supports:
* Fetching ID tokens based on service account keys.
* Fetching ID tokens from the compute engine metadata service.
* Using ID tokens in outgoing auth headers.
ID tokens credentials are generally treated similarly to access tokens. To initialize a credentials object that uses ID tokens instead of access tokens, provide a `target_audience` instead of a `scope` when initializing the credentials. For example:
```ruby
access_token_creds = Google::Auth::Credentials.default \
scope: "https://www.googleapis.com/auth/cloud-platform"
id_token_creds = Google::Auth::Credentials.default \
target_audience: "https://example.com/"
```
Then, ID tokens can be applied to headers in the same way:
```ruby
headers = { "Content-Type" => "application/json" }
access_token_creds.client.apply! headers …
```
> feat: Support for ID token credentials

- CHANGELOG.md
- lib/googleauth/version.rb
* Support for ID token credentials.
* Support reading quota_id_project from service account credentials.
<details><summary>Commits since previous release</summary><pre><code>commit c7f82f29f8547acd64b94c524c845cb9dd490e04
Author: Daniel Azuma <dazuma@google.com>
Date:   Tue Apr 7 17:19:29 2020 -0700
feat: Support for ID token credentials.
commit 5b6ef36a670210e49e38ea93e1b0a25ce3616242
Author: David Supplee <dwsupplee@gmail.com>
Date:   Mon Mar 16 15:33:17 2020 +0000
chore: update github url
commit 61c1e64d5b39fec80f1adf758caf32a0239bb262
Author: Daniel Azuma <dazuma@google.com>
Date:   Fri Mar 6 16:56:16 2020 -0800
feat: read quota_project_id from credentials
commit 41f033361410e86f2228ab91a5619b69413e236d
Author: Daniel Azuma <dazuma@google.com>
Date:   Mon Feb 24 15:18:29 2020 -0800 …
> Release google-auth-library-ruby 0.12.0

- lib/googleauth/service_account.rb
- spec/googleauth/apply_auth_examples.rb
`ServiceAccountCredential#apply` wasn't properly applying ID tokens. Fixed.
> fix: Service account credentials properly apply ID tokens

- .rubocop.yml
- Gemfile
- Rakefile
- googleauth.gemspec
- integration/helper.rb
- integration/id_tokens/key_source_test.rb
- lib/googleauth/id_tokens.rb
- lib/googleauth/id_tokens/errors.rb
- lib/googleauth/id_tokens/key_sources.rb
- lib/googleauth/id_tokens/verifier.rb
- test/helper.rb
- test/id_tokens/key_sources_test.rb
- test/id_tokens/verifier_test.rb
The basic logic here was copied from https://github.com/google/google-id-token. ID token verification is now being integrated into the Ruby auth library, and expanded to support IAP and ES256 verification.
See the `lib/googleauth/id_tokens.rb` file as a starting point. It includes documentation on basic usage, and implements the high-level interface. Then, the two parts of this implementation are: **key sources** (`lib/googleauth/id_tokens/key_sources.rb`) which encapsulates the logic around downloading and interpreting public key data from sources such as the Google oauth certs and IAP jwk pages, and the **verifier** (`lib/googleauth/id_tokens/verifier.rb`) which contains the logic to verify a given token and its claims, given a key source.
> feat: Support for ID token validation

- CHANGELOG.md
- lib/googleauth/application_default.rb
- lib/googleauth/compute_engine.rb
- spec/googleauth/compute_engine_spec.rb
GCECredentials doesn't currently allow scopes to be passed through.
Although not documented the metadata server does support a `scopes` parameter when requesting an access token, at least when running in "workload identity" mode on GKE.
As it's not documented, I'm unsure of the behaviour when requesting multiple scopes (should they be space separated, comma separated, or passed as a parameter array?).
I'm also unsure whether this will break in non-workload identity environments?
> Allow scope to be passed through on GKE

- lib/googleauth/compute_engine.rb
- spec/googleauth/compute_engine_spec.rb
Fixes #274 
When sending the scopes query parameter to the metadata server, comma-delimits instead of space-delimits multiple scopes (correcting #264). On Cloud Run, space (i.e. plus) delimiting the scopes results in a 500 from the metadata server.
> fix: Fix errors when requesting an access token for multiple scopes

- CHANGELOG.md
- lib/googleauth/version.rb
* Honor GCE_METADATA_HOST environment variable
* Fix errors in some environments when requesting an access token for multiple scopes
<details><summary>Commits since previous release</summary><pre><code>commit 6f71d62a6a850aeffd7a829935dab43aae209611
Author: Daniel Azuma <dazuma@google.com>
Date:   Fri Oct 9 09:51:49 2020 -0700
fix: Fix errors when requesting an access token for multiple scopes
commit 3cdb5a8de7dfeeded3c83f4a24a7e3bd96120b2f
Author: Daniel Azuma <dazuma@google.com>
Date:   Fri Oct 9 09:32:26 2020 -0700
feat: Honor GCE_METADATA_HOST environment variable
commit c1e0f44486dce132a0dcab59c9af3c118f6e748d
Author: Justin Beckwith <justin.beckwith@gmail.com>
Date:   Wed Sep 16 15:26:45 2020 -0700
chore: add CODEOWNERS (#273)
</code></pre></details>
This pull request was generated …
> Release google-auth-library-ruby 0.14.0

- lib/googleauth/credentials.rb
- spec/googleauth/credentials_spec.rb
Cause class parameters on credential classes (such as scope) to inherit from superclasses if not set in the subclass. This makes setting these parameters via class methods, behave consistently with setting them as constants (which already inherit from superclasses by virtue of Ruby's constant lookup rules).
ref: https://github.com/googleapis/google-cloud-ruby/issues/8610
> feat: Credential parameters inherit from superclasses

- lib/googleauth/credentials.rb
- lib/googleauth/service_account.rb
- spec/googleauth/credentials_spec.rb
- spec/googleauth/service_account_spec.rb
This change provides support for GAPIC clients to default to self-signed JWT credentials when using a service account when custom scopes are not provided. It uses an "opt-in" model in that the client library (or end-user) needs to enable self-signed JWT support explicitly. This is because of the requirement that self-signed JWT must be disabled if the endpoint is not the service default. The credentials classes know nothing about the endpoint and cannot make this determination themselves, so to avoid breakage, the feature is disabled by default. As the next step, the Ruby GAPIC microgenerator will be enhanced to determine whether it is safe to turn on self-signed JWT (by comparing the actual endpoint with the default endpoint), and pass that information down into the credential.
This PR …
> [REBASE MERGE] Use self-signed JWT when given default scopes

- lib/googleauth/credentials.rb
- spec/googleauth/credentials_spec.rb
We have some test cases in ruby-docs-samples that use Credentials classes without ever setting paths or env_vars. (This is not a valid production case, but we do run into it in some of our tests in other repos.) It causes an exception because the recent change to "inherit" these values from superclasses, causes the field to default to `nil` rather than the empty array. Fixed. Also updated the yardocs to make this more clear.
> fix: Fix crash when using a client credential without any paths or env_vars set

- lib/googleauth/service_account.rb
This was causing a significant slowdown when making self-signed JWT calls in an environment where gcloud is present.
> fix: Stop attempting to get the project from gcloud when applying self-signed JWTs

- .repo-metadata.json
Add an additional field called library_type to the .repo-metadata.json file. This is part of internal issue #184315365.
> chore: add library_type to .repo-metadata.json

- lib/googleauth/credentials_loader.rb
CredentialsLoader shells out to gcloud which causes a reauth prompt to
appear if the user's credentials have been expired. We should close
stdin and stderr so the shelling out silently fails and we return nil
instead.
If we don't do this we can randomly get prompts as follows:
```
Reauthentication required.
Please enter your password:
```
> CredentialsLoader: close stdin and stderr to prevent reauth

- README.md
A quick documentation update to add an example of creating a service worker auth from the environment
> Add `ServiceAccountCredentials.from_env` example

- README.md
closes: #351
I think it seems reasonable and simple to initialize `user_id` to `ENV['USER']` for this command-line example, but I am open to other ideas as well, such as using [Etc](https://ruby-doc.org/stdlib-3.0.2/libdoc/etc/rdoc/Etc.html).
> docs: Fix sample in README.md

- .github/workflows/ci.yml
- Gemfile
This PR adds an entry for Ruby 3.1 to the CI matrix.
In addition to that change, the version restriction on the Coveralls gem was upgraded from '~> 0.7' to '~> 0.8', mitigating errors seen in the Coveralls runs.
On my fork, when the CI config is updated to allow it, everything runs green.
> Add Ruby 3.1 to the CI matrix

- googleauth.gemspec
Relax the gemspec to allow dependency on Faraday 2.x.
Closes #355
> fix: Support Faraday 2

- spec/spec_helper.rb
- load_middleware is made private in later versions of Faraday
> chore: use public method lookup_middleware

- README.md
Per @dazuma:
> yeah it’s supposed to be GA.
closes: #375
> chore: remove alpha declaration from README.md

- README.md
I spent a *long* time figuring out how to do this properly. The docs on
domain-wide delegation don't really make it clear that `sub` has to
be set in order to take advantage of those settings. It seems to me like
this is the easiest way to run domain-wide delegation with this gem, but
if there's an easier way I'm all ears!
> Add instructions for 3-legged-oauth

- lib/googleauth/credentials_loader.rb
`Google::Auth::CredentialsLoader` is no longer needed memorized helper methods provided by `Memoist` module.
So, I removed `extend Memoist`.
> Avoid needless extend module with Memoist

- lib/googleauth/base_client.rb
- lib/googleauth/credentials.rb
- lib/googleauth/credentials_loader.rb
- lib/googleauth/default_credentials.rb
- lib/googleauth/external_account.rb
- lib/googleauth/external_account/aws_credentials.rb
- lib/googleauth/external_account/base_credentials.rb
- lib/googleauth/helpers/connection.rb
- lib/googleauth/oauth2/sts_client.rb
- lib/googleauth/service_account.rb
- lib/googleauth/signet.rb
- spec/googleauth/apply_auth_examples.rb
- spec/googleauth/external_account/aws_credentials_spec.rb
- spec/googleauth/external_account/aws_request_signer_spec.rb
- spec/googleauth/external_account_spec.rb
- spec/googleauth/oauth2/sts_client_spec.rb
This is a wrap of https://github.com/googleapis/google-auth-library-ruby/pull/414
Will continue fix on this one.
> feat: aws credential. Wrap all Ryan & Robert's change

- lib/googleauth/application_default.rb
- spec/googleauth/get_application_default_spec.rb
**CONTEXT:** 
While deploying a couple of services on `Cloud RUN`:
1. service A running with service account A
2. service B running with service account B
3. I added `roles/run.invoker` for service account B on service A.
I expected to be able to retrieve an ID token and be able to call service A from service B. After some debugging I realised I was getting an `access_token` rather then an `id_token`.
I tracked it down to the GCECredentials instantiation only passing the scope to the subclass of the [Signet::Oauth2::Client](https://github.com/googleapis/signet/blob/main/lib/signet/oauth_2/client.rb#L95), hence not being able to pass the `target_audience` for retrieve an `id_token`
I believe this should fix: https://github.com/googleapis/google-auth-library-ruby/issues/299
> fix: GCECredentials - Allow retrieval of ID token

- lib/googleauth/id_tokens.rb
Comments in the `Google::Auth::IDTokens` class that should be `iss` are `aud`.
This PR corrects the comment to `iss` and changes it so that the generated documentation also has the expected description.
Thank you for reviewing.
> docs: fixed iss argument and description in comments of IDTokens

- lib/googleauth/web_user_authorizer.rb
Replace `request[]` calls with `request.params[]`. To fix the deprecation warnings in:
Rack 3.x: https://github.com/rack/rack/blob/3-0-stable/lib/rack/request.rb#L608
Rack 2.x: https://github.com/rack/rack/blob/2-2-stable/lib/rack/request.rb#L531
> chore: Fix rack deprecation warnings.

- .github/sync-repo-settings.yaml
- .github/workflows/ci.yml
- Gemfile
- googleauth.gemspec
- lib/googleauth/application_default.rb
- lib/googleauth/compute_engine.rb
- lib/googleauth/external_account/base_credentials.rb
- spec/googleauth/apply_auth_examples.rb
- spec/googleauth/compute_engine_spec.rb
- spec/googleauth/get_application_default_spec.rb
This is a prerequisite for proper universe_domain support. It removes the code that makes direct calls to the Metadata Server (to determine GCE residence and to fetch Metadata-provided access tokens), and instead delegates to the more robust code in the google-cloud-env 2.0 gem.
Also drops support for Ruby 2.6 since google-cloud-env 2.0 also drops Ruby 2.6.
Also closes #444.
> feat: Use google-cloud-env for more robust Metadata Service access

- lib/googleauth/credentials.rb
- spec/googleauth/credentials_spec.rb
The `Google::Auth::Credentials` class (used by GAPICs) didn't use the normal `make_creds` mechanism used by the rest of the auth system, and thus didn't construct the correct subclass of `Signet::OAuth2::Client` when reading from a custom file path or a custom hash. Instead, it just constructed an instance of the `Signet::OAuth2::Client` base class and hoped for the best. As a result, some key features that were implemented in subclasses were not working, including self-signed JWT authentication, and pretty much all of external credentials.
This change delegates back to `make_creds` instead of constructing the `Signet::OAuth2::Client` base class. This also allows us to remove some of the client options mapping being done (which was duplicating code in …
> fix: Client library credentials provide correct self-signed JWT and external account behavior when loading from a file path or JSON data

- README.md
- lib/googleauth/user_authorizer.rb
- lib/googleauth/web_user_authorizer.rb
- spec/googleauth/user_authorizer_spec.rb
- spec/googleauth/web_user_authorizer_spec.rb
> feat: add PKCE to 3 Legged OAuth exchange

- spec/googleauth/external_account/pluggable_credentials_spec.rb
The not enabled spec will fail when another spec has set the ENV before the spec is run.
> fix(spec): Set ENV for not enabled spec

- lib/googleauth/base_client.rb
- lib/googleauth/external_account/base_credentials.rb
- lib/googleauth/token_store.rb
It is not advisable to raise  NotImplementedError for errors that are not platform errors, such as fsync or fork.
Replace with NoMethodError, which inherits from StandardError.
> refactor: Use NoMethodError for base classes

- lib/googleauth/compute_engine.rb
- lib/googleauth/signet.rb
- spec/googleauth/compute_engine_spec.rb
- spec/googleauth/service_account_spec.rb
Looks like this was never implemented, with the result that ID token credential objects stopped working when the token expired.
> fix: Fixed parsing of expiration timestamp from ID tokens

- .rubocop.yml
- lib/googleauth/compute_engine.rb
- lib/googleauth/credentials.rb
- spec/googleauth/compute_engine_spec.rb
This is Ruby's response to internal issue b/349488459. In this PR, we add a (temporary, optional) attribute (`disable_universe_domain_check`) to credential objects that signals the credential may incorrectly claim googleapis as its universe domain. This will be used for GCECredentials temporarily; when set (which for now it will be), GCECredentials will not query the metadata server for universe domain but will instead hard-code `googleapis.com`. Then, the client libraries (in gapic-common, via https://github.com/googleapis/gapic-generator-ruby/pull/1119) will check for the `disable_universe_domain_check` attribute, and if present and set, will not perform the universe domain consistency check. This will effectively stop universe domain MDS calls and checks for GCE credentials while …
> fix: Temporarily disable universe domain query from GCE metadata server

- googleauth.gemspec
- lib/googleauth/base_client.rb
- lib/googleauth/compute_engine.rb
- lib/googleauth/credentials.rb
- lib/googleauth/external_account/base_credentials.rb
- lib/googleauth/service_account.rb
- lib/googleauth/signet.rb
- spec/googleauth/apply_auth_examples.rb
- spec/googleauth/credentials_spec.rb
Adds a `logger` attribute to each credential type (via BaseClient) and a pass-through from the high-level Credential class. The value is `nil` by default, but when set, certain events such as JWT application and OAuth2 token exchange are logged. Tokens are obfuscated via sha256.
> feat: Provide opt-in debug logging

- lib/googleauth/compute_engine.rb
- spec/googleauth/compute_engine_spec.rb
As part of the logging work, to tamp down on the possible glut of logs on startup in high-traffic environments, we stopped eagerly fetching tokens from the client library credentials object. This was intended not to make any functional difference, because credential objects generally fetch their own tokens just-in-time when requested.
However, #508 revealed one case we missed: GCECredentials do not have a `universe_domain` set until the token is fetched, since the universe domain comes from the metadata service. Thus, client libraries would fail to initialize with a universe domain mismatch error. This happens *only*:
* for GCECredentials, as all other credential types get their universe domain from the input (e.g. json key file), **and**
* if the `gapic-common` gem is older than 0.23.0, …
> fix: GCECredentials lazily fetches from the metadata server to ensure a universe domain is known

- lib/googleauth/compute_engine.rb
- lib/googleauth/credentials.rb
- lib/googleauth/default_credentials.rb
- lib/googleauth/impersonated_service_account.rb
- lib/googleauth/service_account.rb
- lib/googleauth/signet.rb
- lib/googleauth/user_refresh.rb
- spec/googleauth/apply_auth_examples.rb
- spec/googleauth/compute_engine_spec.rb
- spec/googleauth/credentials_spec.rb
- spec/googleauth/impersonated_service_account_spec.rb
- spec/googleauth/service_account_spec.rb
- spec/googleauth/signet_spec.rb
- spec/googleauth/user_refresh_spec.rb
- spec/spec_helper.rb
feat: create impersonated service credentials
feat: add duplication mechanism to various credentials to support "re-scoping" them for IAM requests
> feat: create impersonated service credentials

- lib/googleauth/compute_engine.rb
- lib/googleauth/service_account.rb
- lib/googleauth/user_refresh.rb
The `update!` method is public in `Signet::OAuth2::Client`. #499 made it private in some subclasses, causing a regression for certain workflows. This makes the method public again.
Fixes #515
> fix: Signet client subclasses no longer make the `update!` method private

- lib/googleauth.rb
- lib/googleauth/api_key.rb
- lib/googleauth/bearer_token.rb
- test/bearer_token_test.rb
Bearer tokens are strings representing an authorization grant. They can be OAuth2 ("ya.29") tokens, JWTs, IDTokens -- anything that is sent as a `Bearer` in an `Authorization` header.
This new credentials type should be used when the end-user is managing the authentication token separately, e.g. with a separate service.
> feat: add BearerToken credentials

- lib/googleauth/credentials_loader.rb
I think the spirit of https://github.com/googleapis/google-auth-library-ruby/commit/990250345d6af31de1066c08c0b3b42692ae263c was to prevent `gcloud` from popping out of the console and hanging. Unfortunately, this will always close the subprocess and return an empty string.
This causes downstream issues, for example when initializing a new BigQuery client [0] that relies on the credential to carry the `project_id`.
Adding `--quiet` will disable interactive prompts and either attempt to use defaults or error.
0. https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-bigquery/lib/google/cloud/bigquery.rb
> fix: Get the project_id from gcloud

- lib/googleauth/helpers/connection.rb
```
googleauth-1.13.1/lib/googleauth/helpers/connection.rb:27: warning: attribute accessor as module_function
```
This code was introduced in 1354b076a159d223b737e5b1f27dde0463eb5292.
`module_function` cause the next methods to be defined as both class methods and private instance methods, but the class method part is never used, hence directly declaring them as private is simpler and avoid the warning.
> fix: `attribute accessor as module_function` warning

- .kokoro/release.cfg
- .kokoro/release.sh
Details:
* Switched release job to use the dedicated release image instead of the one shared with CI jobs
* Stopped loading docuploader_credentials from secret manager in favor of using ADC
* Stopped installing toys from the release script since it is present in the image already
* Stopped uploading documentation to googleapis.dev (but retained upload to cloud-rad)
> chore: Updates to release job config

- lib/googleauth/compute_engine.rb
- spec/googleauth/compute_engine_spec.rb
The `x ? true : false` idiom is now getting flagged by rubocop under `Style/RedundantCondition`. I would argue this is a false positive, but I don't have confidence that is a popular enough opinion to cause rubocop to revert its behavior. In any case, we can avoid the problem by making the change in this PR. This does change the internal functionality, as `@universe_domain_overridden` is now merely truthy/falsey rather than strictly `true` or `false`. However, it should only get used internally (in a context where we don't care about the strict type), so that shouldn't matter.
> chore: Fix new rubocop warnings

- Credentials.md
- lib/googleauth/api_key.rb
- lib/googleauth/base_client.rb
- lib/googleauth/bearer_token.rb
- lib/googleauth/compute_engine.rb
- lib/googleauth/external_account/base_credentials.rb
- lib/googleauth/external_account/external_account_utils.rb
- lib/googleauth/iam.rb
- lib/googleauth/id_tokens/key_sources.rb
- lib/googleauth/id_tokens/verifier.rb
- lib/googleauth/impersonated_service_account.rb
- lib/googleauth/scope_util.rb
- lib/googleauth/service_account.rb
- lib/googleauth/service_account_jwt_header.rb
- lib/googleauth/user_authorizer.rb
- lib/googleauth/user_refresh.rb
- test/helper.rb
- test/principal_test.rb
This PR adds a `principal` getter to credentials. The `principal` is safe to log and is implemented as follows:
1. APIKeyCredentials - returns :api_key
2. BearerTokenCredentials - returns :bearer_token
3. GCECredentials - returns :gce_metadata
4. IAMCredentials - returns the selector
5. ServiceAccountCredentials - returns the service account email (issuer)
6. ServiceAccountJwtHeaderCredentials - returns the service account email (issuer)
7. ImpersonatedServiceAccountCredentials - returns the source principal when available, or :unknown
8. UserRefreshCredentials - returns client_id or falls back to :user_refresh
9. UserAuthorizer - returns the client ID
10. ExternalAccount::BaseCredentials - returns the audience
Also added a `Credentials.md` documenting the available credentials.
There are …
> docs: add summary documentation on credentials types and improve YARD comments

- googleauth.gemspec
Makes us compatible with JWT 1.x, 2.x, and 3.x. I've verified our usage remains compatible with 3.x.
Closes #541
> feat: Support for JWT 3.x
